CREATE TABLE  GCG_5327_Absence (
 "ReqID" CHAR(6),
 "Employee" CHAR(5),
 "Dept" CHAR(4),
 "Shift" CHAR(1),
 "Absence_Desc" CHAR(20),
 "DateIn" DATE,
 "TimeInChar" CHAR(5),
 "TimeIn" CHAR(6),
 "DateOut" DATE,
 "TimeOutChar" CHAR(5),
 "TimeOut" CHAR(6),
 "Hours" CHAR(8),
 "HoursHH" NUMERIC(2,0),
 "HoursMM" NUMERIC(2,0),
 "Note" CHAR(500),
 "EC" CHAR(2),
 "ECDescr" CHAR(30),
 "Paid" CHAR(1),
 "Status" VARCHAR(10),
 "ProcByUser" CHAR(8),
 "ProcByUserName" CHAR(30),
 "ProcByEmp" CHAR(5),
 "ProcByEmpName" CHAR(30),
 "ProcNote" CHAR(500),
 "Seq" CHAR(2),
 "DateTimeProcess" DATETIME,
 "Email" BIT DEFAULT '0' NOT NULL );
